"""add avatar and panorama in group

Revision ID: d70b07c5ccb0
Revises: 81129ab0fec0
Create Date: 2025-02-23 22:37:38.108721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70b07c5ccb0'
down_revision: Union[str, None] = '81129ab0fec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('Group', sa.Column('panorama', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Group', 'panorama')
    op.drop_column('Group', 'avatar')
    # ### end Alembic commands ###
